import { StyleSheet } from "react-native";
import { Colors } from "@/constants/Colors";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Colors.light.background,
    },
    header: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 24,
        paddingTop: 60,
        paddingBottom: 20,
        backgroundColor: Colors.light.background,
    },
    backButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: Colors.light.primaryLight,
        justifyContent: "center",
        alignItems: "center",
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: "700",
        color: Colors.light.text,
        letterSpacing: -0.1,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: Colors.light.background,
    },
    errorContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        gap: 20,
        backgroundColor: Colors.light.background,
    },
    errorText: {
        fontSize: 18,
        color: Colors.light.text,
        fontWeight: "600",
    },
    backLink: {
        color: Colors.light.primary,
        fontSize: 16,
        fontWeight: "700",
    },
    scrollContent: {
        paddingBottom: 120,
    },
    serviceCard: {
        flexDirection: "row",
        backgroundColor: Colors.light.background,
        marginHorizontal: 24,
        padding: 14,
        borderRadius: 18,
        borderWidth: 1,
        borderColor: Colors.light.border,
        marginBottom: 24,
        shadowColor: "#8C5240",
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.08,
        shadowRadius: 10,
        elevation: 3,
        alignItems: "center",
    },
    serviceImage: {
        width: 80,
        height: 80,
        borderRadius: 14,
        backgroundColor: Colors.light.card,
    },
    serviceInfo: {
        flex: 1,
        marginLeft: 16,
        justifyContent: "center",
    },
    serviceTitle: {
        fontSize: 16,
        fontWeight: "700",
        color: Colors.light.text,
        marginBottom: 4,
        letterSpacing: -0.1,
    },
    therapistName: {
        fontSize: 13,
        color: Colors.light.primary,
        fontWeight: "600",
        marginBottom: 8,
    },
    serviceMeta: {
        flexDirection: "row",
        gap: 12,
    },
    metaItem: {
        flexDirection: "row",
        alignItems: "center",
        gap: 4,
        backgroundColor: Colors.light.card,
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 8,
    },
    metaText: {
        fontSize: 12,
        color: Colors.light.text,
        fontWeight: "600",
    },
    sectionContainer: {
        marginBottom: 24,
    },
    sectionTitle: {
        fontSize: 17,
        fontWeight: "700",
        color: Colors.light.text,
        paddingHorizontal: 24,
        marginBottom: 8,
        letterSpacing: -0.1,
    },
    selectedDateText: {
        fontSize: 13,
        color: Colors.light.icon,
        paddingHorizontal: 24,
        marginBottom: 16,
    },
    calendarScroll: {
        paddingHorizontal: 24,
        gap: 10,
    },
    dayCard: {
        width: 62,
        height: 80,
        borderRadius: 16,
        backgroundColor: Colors.light.background,
        borderWidth: 1.5,
        borderColor: Colors.light.border,
        justifyContent: "center",
        alignItems: "center",
        gap: 4,
    },
    dayCardActive: {
        backgroundColor: Colors.light.primary,
        borderColor: Colors.light.primary,
    },
    dayName: {
        fontSize: 11,
        color: Colors.light.icon,
        fontWeight: "600",
        textTransform: "capitalize",
    },
    dayNameActive: {
        color: "rgba(255,255,255,0.8)",
    },
    dayNumber: {
        fontSize: 20,
        fontWeight: "700",
        color: Colors.light.text,
    },
    dayNumberActive: {
        color: "#fff",
    },
    timeGrid: {
        flexDirection: "row",
        flexWrap: "wrap",
        paddingHorizontal: 24,
        gap: 10,
    },
    timeSlot: {
        flexBasis: "30%",
        paddingVertical: 12,
        borderRadius: 12,
        backgroundColor: Colors.light.background,
        borderWidth: 1.5,
        borderColor: Colors.light.border,
        alignItems: "center",
    },
    timeSlotActive: {
        backgroundColor: Colors.light.primary,
        borderColor: Colors.light.primary,
    },
    timeText: {
        fontSize: 14,
        fontWeight: "600",
        color: Colors.light.text,
    },
    timeTextActive: {
        color: "#fff",
        fontWeight: "700",
    },
    bottomBar: {
        position: "absolute",
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: Colors.light.background,
        paddingHorizontal: 24,
        paddingTop: 16,
        paddingBottom: 32,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        borderTopWidth: 1,
        borderTopColor: Colors.light.border,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.06,
        shadowRadius: 10,
        elevation: 12,
    },
    priceContainer: {
        gap: 2,
    },
    totalLabel: {
        fontSize: 12,
        color: Colors.light.icon,
        fontWeight: "500",
    },
    totalPrice: {
        fontSize: 22,
        fontWeight: "800",
        color: Colors.light.primary,
        letterSpacing: -0.3,
    },
    confirmButton: {
        backgroundColor: Colors.light.primary,
        paddingHorizontal: 28,
        paddingVertical: 15,
        borderRadius: 14,
        shadowColor: Colors.light.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.35,
        shadowRadius: 8,
        elevation: 5,
    },
    confirmButtonDisabled: {
        opacity: 0.5,
        shadowOpacity: 0,
    },
    confirmButtonText: {
        color: "#fff",
        fontSize: 16,
        fontWeight: "700",
        letterSpacing: 0.1,
    },
})
