import { StyleSheet, Dimensions, Platform } from "react-native";
import { Colors } from "@/constants/Colors";

export const { width } = Dimensions.get('window');
export const SIDEBAR_WIDTH = width * 0.85;

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Colors.light.background,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 24,
        paddingTop: 60,
        paddingBottom: 20,
    },
    overlay: {
        flex: 1,
    },
    backdrop: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: '#000',
    },
    notificationButton: {
        width: 42,
        height: 42,
        borderRadius: 21,
        backgroundColor: Colors.light.primaryLight,
        justifyContent: "center",
        alignItems: "center",
        position: "relative",
    },
    sidebar: {
        position: 'absolute',
        left: 0,
        top: 0,
        bottom: 0,
        width: SIDEBAR_WIDTH,
        backgroundColor: Colors.light.background,
        shadowColor: '#000',
        shadowOffset: { width: -2, height: 0 },
        shadowOpacity: 0.15,
        shadowRadius: 16,
        elevation: 20,
        zIndex: 100,
    },
    sidebarHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingBottom: 20,
        paddingTop: Platform.OS === 'ios' ? 60 : 40,
        borderBottomWidth: 1,
        borderBottomColor: Colors.light.border,
    },
    title: {
        fontSize: 22,
        fontWeight: '700',
        color: Colors.light.text,
        letterSpacing: -0.2,
    },
    listContent: {
        padding: 16,
        paddingBottom: 40,
    },
    itemCallback: {
        flexDirection: 'row',
        padding: 14,
        borderRadius: 16,
        backgroundColor: Colors.light.background,
        marginBottom: 10,
        borderWidth: 1,
        borderColor: Colors.light.border,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.04,
        shadowRadius: 4,
        elevation: 1,
    },
    unreadItem: {
        backgroundColor: Colors.light.primaryLight,
        borderColor: Colors.light.primary,
    },
    iconContainer: {
        marginRight: 12,
        marginTop: 2,
        width: 38,
        height: 38,
        borderRadius: 19,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: Colors.light.card,
    },
    unreadIconContainer: {
        backgroundColor: Colors.light.primary,
    },
    markReadButton: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: Colors.light.background,
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft: 8,
        alignSelf: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.08,
        shadowRadius: 2,
        elevation: 2,
        borderWidth: 1,
        borderColor: Colors.light.border,
    },
    textContainer: {
        flex: 1,
    },
    itemTitle: {
        fontSize: 15,
        fontWeight: '600',
        color: Colors.light.text,
        marginBottom: 3,
        letterSpacing: -0.1,
    },
    unreadTitle: {
        color: Colors.light.primary,
        fontWeight: '700',
    },
    itemBody: {
        fontSize: 13,
        color: Colors.light.icon,
        lineHeight: 19,
        marginBottom: 6,
    },
    itemTime: {
        fontSize: 11,
        color: Colors.light.icon,
        fontWeight: '500',
    },
    dot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: Colors.light.primary,
        position: 'absolute',
        top: 16,
        right: 16,
    },
    emptyState: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingTop: 80,
        gap: 12,
    },
    emptyText: {
        fontSize: 15,
        color: Colors.light.icon,
        fontWeight: '500',
    },
    notificationBadge: {
        position: "absolute",
        top: 6,
        right: 6,
        backgroundColor: Colors.light.error,
        minWidth: 16,
        height: 16,
        borderRadius: 8,
        justifyContent: "center",
        alignItems: "center",
        borderWidth: 1.5,
        borderColor: Colors.light.background,
        zIndex: 10,
        paddingHorizontal: 2,
    },
    notificationBadgeText: {
        color: "#fff",
        fontSize: 9,
        fontWeight: "700",
        textAlign: "center",
    },
})
